#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${HOME}/work/robotarm/mt4_isaac_lab_task"
BEST_FILE="${PROJECT_DIR}/logs/plots/best_checkpoint.txt"

cd ~/work/isaac/src/IsaacLab
unset CMEEL_PREFIX
export DISPLAY=:1
if [[ -z "${TERM:-}" || "${TERM}" == "dumb" ]]; then
  export TERM=xterm-256color
fi

TASK_NAME="Isaac-MT4-Simplified-Reach-Direct-v0"
DEMO_SECONDS="${DEMO_SECONDS:-90}"

if [[ ! -s "${BEST_FILE}" ]]; then
  echo "[ERROR] best_checkpoint.txt was not found or is empty."
  echo "        Expected path: ${BEST_FILE}"
  echo "        Run plot_and_select_best.sh after training first."
  exit 1
fi

CHECKPOINT="$(tr -d '\r\n' < "${BEST_FILE}")"
if [[ ! -f "${CHECKPOINT}" ]]; then
  echo "[ERROR] The checkpoint recorded in best_checkpoint.txt does not exist:"
  echo "        ${CHECKPOINT}"
  echo "        Re-run plot_and_select_best.sh to refresh the selected checkpoint."
  exit 1
fi

if command -v xdpyinfo >/dev/null 2>&1 && ! xdpyinfo -display "${DISPLAY}" >/dev/null 2>&1; then
  echo "[WARN] DISPLAY=${DISPLAY} is not accessible from this shell."
  echo "       If you are using VNC, run this in the VNC terminal first:"
  echo "       xhost +SI:localuser:${USER}"
fi

export MT4_REACH_TRAINING_MODE=stage4_center
export MT4_REACH_RESET_MODE="${MT4_REACH_RESET_MODE:-default}"
export MT4_REACH_MOVING_PREGRASP="${MT4_REACH_MOVING_PREGRASP:-1}"
export MT4_REACH_MOVING_PREGRASP_GOAL="${MT4_REACH_MOVING_PREGRASP_GOAL:-center}"
export MT4_REACH_MOVING_PREGRASP_STEPS="${MT4_REACH_MOVING_PREGRASP_STEPS:-5}"
export MT4_REACH_MOVING_PREGRASP_FINAL_FRACTION="${MT4_REACH_MOVING_PREGRASP_FINAL_FRACTION:-1.0}"
export MT4_REACH_MOVING_PREGRASP_STEP_RADIUS="${MT4_REACH_MOVING_PREGRASP_STEP_RADIUS:-0.045}"
export MT4_REACH_MOVING_PREGRASP_HOLD_STEPS="${MT4_REACH_MOVING_PREGRASP_HOLD_STEPS:-2}"
export MT4_REACH_MOVING_PREGRASP_REWARD_WEIGHT="${MT4_REACH_MOVING_PREGRASP_REWARD_WEIGHT:-24.0}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_WEIGHT="${MT4_REACH_MOVING_PREGRASP_FUNNEL_WEIGHT:-14.0}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_DEPTH="${MT4_REACH_MOVING_PREGRASP_FUNNEL_DEPTH:-0.110}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_MIN_RADIUS="${MT4_REACH_MOVING_PREGRASP_FUNNEL_MIN_RADIUS:-0.024}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_MAX_RADIUS="${MT4_REACH_MOVING_PREGRASP_FUNNEL_MAX_RADIUS:-0.095}"
export MT4_REACH_MOVING_PREGRASP_EXP_WEIGHT="${MT4_REACH_MOVING_PREGRASP_EXP_WEIGHT:-0.36}"
export MT4_REACH_MOVING_PREGRASP_SHELL_WEIGHT="${MT4_REACH_MOVING_PREGRASP_SHELL_WEIGHT:-0.34}"
export MT4_REACH_MOVING_PREGRASP_SHELL_SIZE="${MT4_REACH_MOVING_PREGRASP_SHELL_SIZE:-0.005}"
export MT4_REACH_MOVING_PREGRASP_EXP_SCALE="${MT4_REACH_MOVING_PREGRASP_EXP_SCALE:-0.038}"
export MT4_REACH_DESIRED_TOUCH_DISTANCE="${MT4_REACH_DESIRED_TOUCH_DISTANCE:-0.0}"
export MT4_REACH_FINAL_CENTER_RADIUS="${MT4_REACH_FINAL_CENTER_RADIUS:-0.050}"
export MT4_REACH_ACTION_SCALE="${MT4_REACH_ACTION_SCALE:-0.024}"

echo "[INFO] MT4 blue-funnel classroom demo"
echo "[INFO] checkpoint=${CHECKPOINT}"
echo "[INFO] Random red target is generated by the task each episode."
echo "[INFO] Blue guide goal=${MT4_REACH_MOVING_PREGRASP_GOAL}, steps=${MT4_REACH_MOVING_PREGRASP_STEPS}, radius=${MT4_REACH_MOVING_PREGRASP_STEP_RADIUS}, hold=${MT4_REACH_MOVING_PREGRASP_HOLD_STEPS}"
echo "[INFO] One-shot shell reward: weight=${MT4_REACH_MOVING_PREGRASP_SHELL_WEIGHT}, shell_size=${MT4_REACH_MOVING_PREGRASP_SHELL_SIZE}"
echo "[INFO] Exponential approach reward: weight=${MT4_REACH_MOVING_PREGRASP_EXP_WEIGHT}, exp_scale=${MT4_REACH_MOVING_PREGRASP_EXP_SCALE}"
echo "[INFO] DEMO_SECONDS=${DEMO_SECONDS}"

if [[ "${DEMO_SECONDS}" == "0" ]]; then
  ./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/play.py \
    --task "${TASK_NAME}" \
    --checkpoint "${CHECKPOINT}" \
    --num_envs 1 \
    --real-time \
    "$@"
else
  timeout --foreground "${DEMO_SECONDS}s" \
    ./isaaclab.sh -p scripts/reinforcement_learning/rsl_rl/play.py \
      --task "${TASK_NAME}" \
      --checkpoint "${CHECKPOINT}" \
      --num_envs 1 \
      --real-time \
      "$@"
fi
