#!/usr/bin/env bash
# GUI demo for the smoother Stage-4 blue guide experiment.
set -euo pipefail

PROJECT_DIR="${HOME}/work/robotarm/robotarm_student"

export MT4_REACH_STAGE4_STATE_FILE="${MT4_REACH_STAGE4_STATE_FILE:-${PROJECT_DIR}/data/stage4_safe_entry_states/latest.pt}"
export MT4_REACH_MOVING_PREGRASP_STEPS="${MT4_REACH_MOVING_PREGRASP_STEPS:-8}"
export MT4_REACH_MOVING_PREGRASP_STEP_RADIUS="${MT4_REACH_MOVING_PREGRASP_STEP_RADIUS:-0.050}"
export MT4_REACH_MOVING_PREGRASP_HOLD_STEPS="${MT4_REACH_MOVING_PREGRASP_HOLD_STEPS:-3}"
export MT4_REACH_MOVING_PREGRASP_REWARD_WEIGHT="${MT4_REACH_MOVING_PREGRASP_REWARD_WEIGHT:-24.0}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_WEIGHT="${MT4_REACH_MOVING_PREGRASP_FUNNEL_WEIGHT:-14.0}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_DEPTH="${MT4_REACH_MOVING_PREGRASP_FUNNEL_DEPTH:-0.105}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_MIN_RADIUS="${MT4_REACH_MOVING_PREGRASP_FUNNEL_MIN_RADIUS:-0.014}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_MAX_RADIUS="${MT4_REACH_MOVING_PREGRASP_FUNNEL_MAX_RADIUS:-0.065}"
export MT4_REACH_MOVING_PREGRASP_EXP_WEIGHT="${MT4_REACH_MOVING_PREGRASP_EXP_WEIGHT:-0.34}"
export MT4_REACH_MOVING_PREGRASP_SHELL_WEIGHT="${MT4_REACH_MOVING_PREGRASP_SHELL_WEIGHT:-0.34}"
export MT4_REACH_MOVING_PREGRASP_SHELL_SIZE="${MT4_REACH_MOVING_PREGRASP_SHELL_SIZE:-0.004}"
export MT4_REACH_MOVING_PREGRASP_EXP_SCALE="${MT4_REACH_MOVING_PREGRASP_EXP_SCALE:-0.032}"
export MT4_REACH_FINAL_INSERTION_WEIGHT="${MT4_REACH_FINAL_INSERTION_WEIGHT:-36.0}"
export MT4_REACH_FINAL_CENTER_RADIUS="${MT4_REACH_FINAL_CENTER_RADIUS:-0.045}"
export MT4_REACH_GRIPPER_ROLL_WEIGHT="${MT4_REACH_GRIPPER_ROLL_WEIGHT:-2.5}"
export MT4_REACH_STAGE4_SUCCESS_MIN_PROGRESS="${MT4_REACH_STAGE4_SUCCESS_MIN_PROGRESS:-0.78}"
export MT4_REACH_STAGE4_SUCCESS_MAX_PROGRESS="${MT4_REACH_STAGE4_SUCCESS_MAX_PROGRESS:-1.08}"
export MT4_REACH_EARLY_TARGET_CLEARANCE="${MT4_REACH_EARLY_TARGET_CLEARANCE:-0.055}"
export MT4_REACH_EARLY_TARGET_CONTACT_PENALTY="${MT4_REACH_EARLY_TARGET_CONTACT_PENALTY:-160.0}"
export MT4_REACH_STAGE4_OVERSHOOT_PENALTY="${MT4_REACH_STAGE4_OVERSHOOT_PENALTY:-18.0}"

"${PROJECT_DIR}/scripts/play_stage4_blue_center_best.sh" "$@"
