#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${HOME}/work/robotarm/robotarm_student"

export MT4_MAX_ITERATIONS="${MT4_MAX_ITERATIONS:-800}"
export MT4_REACH_MOVING_PREGRASP_STEPS="${MT4_REACH_MOVING_PREGRASP_STEPS:-5}"
export MT4_REACH_MOVING_PREGRASP_STEP_RADIUS="${MT4_REACH_MOVING_PREGRASP_STEP_RADIUS:-0.045}"
export MT4_REACH_MOVING_PREGRASP_HOLD_STEPS="${MT4_REACH_MOVING_PREGRASP_HOLD_STEPS:-2}"
export MT4_REACH_MOVING_PREGRASP_REWARD_WEIGHT="${MT4_REACH_MOVING_PREGRASP_REWARD_WEIGHT:-24.0}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_WEIGHT="${MT4_REACH_MOVING_PREGRASP_FUNNEL_WEIGHT:-14.0}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_DEPTH="${MT4_REACH_MOVING_PREGRASP_FUNNEL_DEPTH:-0.110}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_MIN_RADIUS="${MT4_REACH_MOVING_PREGRASP_FUNNEL_MIN_RADIUS:-0.024}"
export MT4_REACH_MOVING_PREGRASP_FUNNEL_MAX_RADIUS="${MT4_REACH_MOVING_PREGRASP_FUNNEL_MAX_RADIUS:-0.095}"
export MT4_REACH_MOVING_PREGRASP_EXP_WEIGHT="${MT4_REACH_MOVING_PREGRASP_EXP_WEIGHT:-0.36}"
export MT4_REACH_MOVING_PREGRASP_SHELL_WEIGHT="${MT4_REACH_MOVING_PREGRASP_SHELL_WEIGHT:-0.34}"
export MT4_REACH_MOVING_PREGRASP_SHELL_SIZE="${MT4_REACH_MOVING_PREGRASP_SHELL_SIZE:-0.005}"
export MT4_REACH_MOVING_PREGRASP_EXP_SCALE="${MT4_REACH_MOVING_PREGRASP_EXP_SCALE:-0.038}"

echo "[INFO] Long blue-funnel Stage-4 curriculum"
echo "[INFO] This is the broad first phase: radius=${MT4_REACH_MOVING_PREGRASP_STEP_RADIUS}, hold=${MT4_REACH_MOVING_PREGRASP_HOLD_STEPS}, iterations=${MT4_MAX_ITERATIONS}"
echo "[INFO] Blue guide uses one-shot distance shells plus exponential center approach reward."
echo "[INFO] After it produces stable guide-following, tighten to 0.035/4 and later 0.018/8."

"${PROJECT_DIR}/scripts/train_stage4_blue_center_128_300.sh" "$@"
